version: '2'

services:
    mysql:
        image: mysql:5.6
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: url_shortner
            MYSQL_USER: url_shortner
            MYSQL_PASSWORD: url_shortner_pass
        ports:
            - "3307:3306"
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./:/var/www/url_shortner
        ports:
            - "8080:80"
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/url_shortner